### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by austing** [gregplaysguitar/django-eventtools#9]
I had some problems when I set TZ_INFO=True in settings.py. In particular, I can't call `    next_occurrence_start = self.next_occurrence(from_date=now)[0]`

```
Traceback (most recent call last):
  File "/Users/Gross/.virtualenvs/whitebox/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Gross/.virtualenvs/whitebox/lib/python2.7/site-packages/wagtail/wagtailcore/views.py", line 25, in serve
    return page.serve(request, *args, **kwargs)
  File "/Users/Gross/.virtualenvs/whitebox/lib/python2.7/site-packages/wagtail/contrib/wagtailroutablepage/models.py", line 101, in serve
    return view(request, *args, **kwargs)
  File "/Users/Gross/Sites/Atelier/whitebox/page/models/events_page.py", line 90, in events_list_view
    self.get_events_list()
  File "/Users/Gross/Sites/Atelier/whitebox/page/models/events_page.py", line 83, in serialize_events_list
    return events_model.preview_serializer(events, many=True).data
  File "/Users/Gross/.virtualenvs/whitebox/lib/python2.7/site-packages/rest_framework/serializers.py", line 658, in data
    ret = super(ListSerializer, self).data
  File "/Users/Gross/.virtualenvs/whitebox/lib/python2.7/site-packages/rest_framework/serializers.py", line 223, in data
    self._data = self.to_representation(self.instance)
  File "/Users/Gross/.virtualenvs/whitebox/lib/python2.7/site-packages/rest_framework/serializers.py", line 598, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/Users/Gross/.virtualenvs/whitebox/lib/python2.7/site-packages/rest_framework/serializers.py", line 447, in to_representation
    attribute = field.get_attribute(instance)
  File "/Users/Gross/.virtualenvs/whitebox/lib/python2.7/site-packages/rest_framework/fields.py", line 401, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/Users/Gross/.virtualenvs/whitebox/lib/python2.7/site-packages/rest_framework/fields.py", line 76, in get_attribute
    instance = getattr(instance, attr)
  File "/Users/Gross/Sites/Atelier/whitebox/page/models/events_page.py", line 264, in next_event_occurrence
    next_occurrence_start = self.next_occurrence(from_date=now)[0]
  File "/Users/Gross/.virtualenvs/whitebox/lib/python2.7/site-packages/eventtools/models.py", line 139, in next_occurrence
    self.all_occurrences(from_date=from_date, to_date=to_date))
  File "/Users/Gross/.virtualenvs/whitebox/lib/python2.7/site-packages/eventtools/models.py", line 23, in first_item
    return next(gen)
  File "/Users/Gross/.virtualenvs/whitebox/lib/python2.7/site-packages/eventtools/models.py", line 54, in combine_occurrences
    next_date = next(gen)
  File "/Users/Gross/.virtualenvs/whitebox/lib/python2.7/site-packages/eventtools/models.py", line 331, in all_occurrences
    inc=True
  File "/Users/Gross/.virtualenvs/whitebox/lib/python2.7/site-packages/dateutil/rrule.py", line 225, in between
    if i > before:
TypeError: can't compare offset-naive and offset-aware datetimes
```

At this point, *i* is `datetime.datetime(2016, 2, 26, 10, 2, tzinfo=<UTC>)`, and *before* is `datetime.datetime(2016, 3, 4, 23, 59, 59)`.

The problem seems to be that *as_datetime* strips off timezone information, but the timezone information is left on the dates used in the generator.

**Comment by austing** [comment]
The following fixes my issue:
https://github.com/gregplaysguitar/django-eventtools/compare/master...austing:master

There are a few other naive datetimes hard-wired elsewhere in models.py, that I think also need to be changed:
```
                    from_date or datetime(1, 1, 1, 0, 0),
                    to_date or datetime(9999, 12, 31, 23, 59),
```

**Comment by gregplaysguitar** [comment]
Ah, thanks for this. I haven't used this lib with timezones yet so that hadn't popped up. I've created a pull request but there are some failing tests, if you want to have a look feel free, otherwise I can look at it later today.

**Comment by austing** [comment]
What a quick response! I'll check it out tomorrow a.m if you haven't by then.
